/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppQuizIdRouteImport } from './routes/app.quiz.$id'
import { Route as AppPlayIdRouteImport } from './routes/app.play.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizIdRoute = AppQuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayIdRoute = AppPlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/history': typeof AppHistoryRoute
  '/app/': typeof AppIndexRoute
  '/app/play/$id': typeof AppPlayIdRoute
  '/app/quiz/$id': typeof AppQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/history': typeof AppHistoryRoute
  '/app': typeof AppIndexRoute
  '/app/play/$id': typeof AppPlayIdRoute
  '/app/quiz/$id': typeof AppQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/create': typeof AppCreateRoute
  '/app/history': typeof AppHistoryRoute
  '/app/': typeof AppIndexRoute
  '/app/play/$id': typeof AppPlayIdRoute
  '/app/quiz/$id': typeof AppQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/create'
    | '/app/history'
    | '/app/'
    | '/app/play/$id'
    | '/app/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/create'
    | '/app/history'
    | '/app'
    | '/app/play/$id'
    | '/app/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/create'
    | '/app/history'
    | '/app/'
    | '/app/play/$id'
    | '/app/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz/$id': {
      id: '/app/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/app/quiz/$id'
      preLoaderRoute: typeof AppQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/play/$id': {
      id: '/app/play/$id'
      path: '/play/$id'
      fullPath: '/app/play/$id'
      preLoaderRoute: typeof AppPlayIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCreateRoute: typeof AppCreateRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlayIdRoute: typeof AppPlayIdRoute
  AppQuizIdRoute: typeof AppQuizIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreateRoute: AppCreateRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlayIdRoute: AppPlayIdRoute,
  AppQuizIdRoute: AppQuizIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
